import React, { Component } from 'react';
import './termsandconditions.component.css';
import { Row,Col, Button, Checkbox as CBox, FormControl} from 'react-bootstrap';

class TermsAndConditionsComponent extends Component{

    render(){
        return(
            <div className="mainTermContainer">
                <h4 className="termsAlign">Terms of Use </h4>
                <p className="versionAlign">Version 1.01 </p>
                <p className="versionAlign">Last revised on: <label className="augAlign">August</label> 1, 2018 </p>   
                <p className="paraColorChange termsLinks">FSNET, LLC dba Vanilla (“FSNET” or “we” or “us”) is providing this website, <a href="http://www.vanillafund.com" target="_blank">www.vanillafund.com</a>, also operating from time to time under <a href="http://www.vanillavc.com" target="_blank">www.vanillavc.com</a>, <a href="http://www.vanillape.com" target="_blank">www.vanillape.com</a> and <a href="http://www.vanillare.com" target="_blank">www.vanillare.com</a> ((collectively with related iOS, Android or other mobile applications, the “Site”), as an information dissemination and processing service. By accessing the Site, clicking “I ACCEPT” upon registration, and/or using the information, tools, content, and features located on the Site, you accept and agree to be bound by this terms of use agreement (“Terms”), as may be amended from time to time. You represent that (1) you have read, understand, and agree to be bound by these Terms, (2) you are of legal age to form a binding contract with us, and (3) you have the authority to enter into the Terms personally or on behalf of the company you have named as the user, and to bind that company to these Terms.  The term “you” refers to the individual or legal entity, as applicable, identified as the user when you register on the Site.  It is your responsibility to be aware of, and to comply with, these Terms and all applicable laws and regulations of any relevant jurisdiction, when using the Site and related services.  <b className="lightBold">If you do not agree to be bound by these Terms, you may not access or use this Site.</b> </p>
                <p className="paraColorChange"><b>ANY DISPUTE OR CLAIM RELATING IN ANY WAY TO YOUR USE OF THE SITE WILL BE GOVERNED AND INTERPRETED BY AND UNDER THE LAWS OF THE STATE OF NEW YORK, CONSISTENT WITH THE FEDERAL ARBITRATION ACT, WITHOUT GIVING EFFECT TO ANY PRINCIPLES THAT PROVIDE FOR THE APPLICATION OF THE LAW OF ANY OTHER JURISDICTION.  THE UNITED NATIONS CONVENTION ON CONTRACTS FOR THE INTERNATIONAL SALE OF GOODS IS EXPRESSLY EXCLUDED FROM THIS AGREEMENT.</b> </p>
                <p>Please note that these Terms are subject to change by FSNET in its sole discretion at any time. When changes are made, we will make a new copy of the Terms available at the Site. We will also update the “Last Updated” date at the top of the Terms. PLEASE REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS. </p>
                <p>We may terminate, change, restrict, suspend or discontinue any aspect of the Site, or your access to it, at any time without notice or liability to you.  </p>
                <h4>Use of the Site </h4>
                <p>The Site, the Site Content (as defined below), and all other information and content available through the Site, are protected by copyright laws throughout the world.  </p>
                <p className="paraColorChange">You agree not to: (a) take any action that imposes an unreasonable load on this Site’s infrastructure; (b) use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site; (c) attempt to decipher, decompile, disassemble or reverse engineer any of the software comprising or making up this Site; (d) delete or alter any material posted on this Site by FSNET or any other person or entity; (e) frame or link to any of the materials or information available on this Site; (f) impersonate any person or entity or misrepresent your affiliation with any other person or entity, whether actual or fictitious, including anyone from this Site or FSNET; (g) obtain or attempt to gain unauthorized access to other computer systems, materials, information or any services available on or through this Site through any means, including through means not intentionally made publicly available or provided for through this Site; (h) engage in spidering, “screen scraping,” “database scraping,” harvesting of e-mail addresses or other personal information, or any other automatic or unauthorized means of accessing, logging-in or registering on this Site, or obtaining lists of users or other information from or through this Site including, without limitation, any information residing on any server or database connected to this Site; (i) use this Site or the content of this Site, including but not limited to the text and images herein and their arrangement, to violate, plagiarize or in any other manner infringe upon the rights of third parties, including without limitation, copyright, trademark, trade secret, confidentiality, contract, patent, rights of privacy or rights of publicity or any other proprietary or legal right; (j) upload, post, publish, distribute or otherwise transmit any information or material which constitutes or contains a virus, spyware, or other harmful component, or which contains any embedded links, advertising, chain letters or pyramid schemes of any kind; (k) disclose any sensitive, proprietary or confidential information, about yourself or anyone else, (l) attempt (or encourage or support anyone else’s attempt) to circumvent, reverse engineer, decrypt, or otherwise alter or interfere with this Site; or (m) use this Site or its services (or any Site Content (as defined below)), in whole or in part, or submit any information to this Site, in violation of any applicable law, rule or regulation. </p>
                <h4>No Solicitation or Investment Advice</h4>
                <p className="paraColorChange">The purpose of this Site <b className="lightBold">(including any portion of this Site available only to investors or fund managers)</b> is limited to providing you with general information on our services and philosophy and disseminating information. We do not render or offer to render investment advice or legal advice through this Site. You expressly agree and acknowledge that we require you toyou’re your own legal counsel and investment advisers for all aspects of using the services on the Site.  WQe provide means for such advisors to be included in access to the Site as “GP Delegates” or “LP Delegates” and encourage you to make use of these features in fulfillment of your commitment to render your own investment and legal advice.  Nothing on this Site constitutes or forms a part of any offer for sale or subscription of, or any invitation to offer to buy or subscribe for, any securities or other financial instruments, nor should it or any part of it form the basis of, or be relied upon in connection with, any contract or commitment whatsoever.  There is no implication that any information contained on this Site is accurate or that there has been no change in such information since the date first posted. Certain places on this Site may contain information created and published by institutions or organizations independent of us or our users. We do not (nor do our users) endorse, approve, certify, or control these materials.  In addition, we do not (nor do our users) guarantee or assume responsibility for the accuracy, completeness, efficacy, timeliness or correct sequencing of information in any material on the Site. Use of such information is voluntary, and reliance on it should be undertaken after an independent review of its accuracy, completeness, efficacy, and timeliness. Finally, reference in this Site to any specific commercial product, process, or service by trade name, trademark, service mark, manufacturer, or otherwise does not constitute or imply endorsement, recommendation, or favoring by us. </p>
                <h4>Intellectual Property </h4>
                <p>As between you and us, we own all rights, title and interest in and to this Site, all the content (including, without limitation, all text, audio, photographs, images, renderings, RSS feeds, podcasts, reports, charts, logos, widgets, gadgets, applets, and video), software, code, data and other materials thereon (collectively, the “Site Content”), the look and feel, design and organization of the Site, and the compilation of the Site Content. Your use of the Site does not grant to you ownership or title of, in, or to any Site Content or any other part of the Site. </p>
                <p>Subject to these Terms, you may access, view, use and display the Site and Site Content on your computer or other Internet-capable device for your own purposes, provided that you comply fully with these Terms. You may not copy or display for redistribution to third parties any portion of the Site or the Site Content without the prior written permission of FSNET, provided that you may download documents from the Site as permitted by the functionality of the Site.  You should be mindful that in almost all cases all such documents are the confidential, trade secret and the subject of obligations of confidentiality under contracts you will have agreed to by using the Site.  </p>
                <p>Copyright © 2018 FSNET, LLC. All rights reserved.</p>
                <p>We hold exclusive trademark rights to FSNET, VANILLAFUND, VANILLAVC, VANILLAPE and VANILLARE and derivations thereof. The trademarks associated with other companies that are published on our Site, including those of our portfolio and anti-portfolio, are owned by their respective owners. You are not permitted to use any trademarks, logos, service marks and trade names (“Marks”) that are displayed on the Site without our prior written consent or the consent of us or such third party which may own the Marks. </p>
                <h4>Security </h4>
                <p className="paraColorChange">While we endeavor to protect the security and integrity of the information we may collect from you via the Site, as described in our Privacy Policy (url), due to the inherent nature of the Internet as an open global communications vehicle, we cannot guarantee that any information, during transmission through the Internet or while stored on our system or otherwise in our care, will be absolutely safe from intrusion by others, such as hackers. A third party could view the information you send in transit by electronic means.  We will have no liability for disclosure of your information due to errors or unauthorized acts of third parties during or after transmission. </p>
                <h4>Release</h4>
                <p>You hereby release and forever discharge FSNET (and our officers, employees, equity owners, members, managers, agents, successors, and assigns, as well as all the affiliates and affiliated parties of the preceding, collectively referred to herein as the “Protected Parties”) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Site (including any interactions with, or act or omission of, other Site users or any Third-Party Sites).  IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” </p>
                <h4>Disclaimer</h4>
                <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE SITE IS AT YOUR SOLE RISK, AND THE SITE AND SITE CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL FAULTS.  FSNET EXPRESSLY DISCLAIMS ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARISING FROM USE OF THE SITE. </p>
                <p>YOU EXPRESSLY AGREE THAT YOUR USE OF THE SITE AND SITE CONTENT IS AT YOUR SOLE RISK. NEITHER WE NOR ANY OF OUR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR CONTENT OR SERVICE PROVIDERS WARRANT THAT USE OF THE SITE WILL BE UNINTERRUPTED OR ERROR FREE. THE SITE MAY BE SUBJECT TO DELAYS OR OTHER DISRUPTIONS.  IN ADDITION, ALTHOUGH THE INFORMATION PROVIDED TO YOU ON THIS SITE IS OBTAINED OR COMPILED FROM SOURCES (INCLUDING, WITHOUT LIMITATION, INFORMATION FROM THIRD PARTIES) WE BELIEVE TO BE RELIABLE, NEITHER WE NOR ANY OF OUR DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, OR CONTENT OR SERVICE PROVIDERS MAKE ANY WARRANTY AS TO (I) THE RESULTS THAT MAY BE OBTAINED FROM YOUR USE OF THE SITE OR SITE CONTENT, (II) THE ACCURACY, CURRENCY OR COMPLETENESS OF THE INFORMATION ON OUR SITE, OR (III) THE RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER MATERIALS DISPLAYED ON, OR DISTRIBUTED THROUGH, OUR SITE.  NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM FSNET OR THROUGH THE SITE WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
                <p>YOU ACKNOWLEDGE AND AGREE THAT FSNET IS NOT LIABLE, AND YOU AGREE NOT TO HOLD FSNET LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF EXTERNAL SITES THAT ARE LINKED TO THE SITE, AND THAT THE RISK OF INJURY FROM SUCH PARTIES RESTS ENTIRETY WITH YOU. YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE. YOU UNDERSTAND THAT FSNET DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE. </p>
                <h4>International Use</h4>
                <p className="paraColorChange">Due to the global nature of the Internet, this Site may be accessed by users in countries other than the United States. We make no warranties that materials on this website are appropriate or available for use in such locations. If it is illegal or prohibited in your country of origin to access or use this Site, then you should not do so. Those who choose to access this Site outside the United States do so on their own initiative and are responsible for compliance with all local laws and regulations. </p>
                <h4>Limitation of Liability </h4>
                <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAWS, IN NO EVENT, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL ANY OF THE PROTECTED PARTIES BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING FROM, OR DIRECTLY OR INDIRECTLY RELATED TO: (1) THE USE OR INABILITY TO USE THE SITE; (2) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED FOR TRANSACTIONS ENTERED INTO THROUGH THE SITE; (3) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (4) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE; OR (5) ANY OTHER MATTER RELATED TO THE SITE, WHETHER BASED ON WARRANTY, COPYRIGHT, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, EVEN IF SUCH PROTECTED PARTY HAS BEEN SPECIFICALLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF YOU ARE DISSATISFIED WITH THIS SITE, OR ANY MATERIALS OR SERVICES ON THIS SITE, OR WITH ANY OF THE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE. </p>
                <h4>Material Non-Public Information</h4>
                <p>The information contained in the Site may include material non-public information.  It is a violation of United States securities laws for a person in possession of material non-public information concerning an issuer to purchase or sell securities of such issuer or to communicate such information to another person under circumstances in which it is reasonably foreseeable that such person is likely to purchase or sell securities.  Many countries outside the United States have similar or in some cases more restrictive rules.  It is solely your responsibility to adhere to any and all applicable laws, rules and regulations regarding material non-public information, and otherwise. </p>
                <h4>Electronic Communications</h4>
                <p>The communications between you and FSNET use electronic means, whether you visit the Site or send FSNET e-mails, texts or other electronic communications, or whether FSNET posts notices on its properties or communicates with you via e-mail, texts or other election communications.  For contractual purposes, you (1) consent to receive communications from FSNET in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that FSNET provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing.  The foregoing does not affect your statutory rights.    </p>
                <h4>Dispute Resolution</h4>
                <p>Please read this Arbitration Agreement carefully.  It is part of your contract with FSNET and affects your rights.  It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER. </p>
                <p className="paraColorChange">(a) <i>Applicability of Arbitration Agreement.</i>  All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms or the use of any product or service provided by FSNET  that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement.  Unless otherwise agreed to, all arbitration proceedings shall be held in English.  This Arbitration Agreement applies to you and FSNET, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms. </p>
                <p className="paraColorChange">(b) <i>Notice Requirement and Informal Dispute Resolution.</i>  Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (“Notice”) describing the nature and basis of the claim or dispute, and the requested relief.  A Notice to FSNET should be sent by certified mail to: FSNET, 210 Morningside Drive, Corte Madera CA 94925  After the Notice is received, you and FSNET may attempt to resolve the claim or dispute informally.  If you and FSNET do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding.  The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled. </p>
                <p className="paraColorChange">(c) <i>Arbitration Rules.</i>  Arbitration shall be initiated through the American Arbitration Association (“AAA”), an established alternative dispute resolution provider (“ADR Provider”) that offers arbitration as set forth in this section.  If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider.  The rules of the ADR Provider shall govern all aspects of the arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms.  The AAA Consumer Arbitration Rules (“Arbitration Rules”) governing the arbitration are available online at www.adr.org or by calling the AAA at 1-800-778-7879.  The arbitration shall be conducted by a single, neutral arbitrator.  Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief.  For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules.  Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise.  If you reside outside of the U.S., the arbitrator shall give the parties reasonable notice of the date, time and place of any oral hearings. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.  If the arbitrator grants you an award that is greater than the last settlement offer that FSNET made to you prior to the initiation of arbitration, FSNET  will pay you the greater of the award or $2,500.00.  Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration and shall pay an equal share of the fees and costs of the ADR Provider. </p>
                <p className="paraColorChange">(d) <i>Additional Rules for Non-Appearance Based Arbitration.</i>  If non-appearance based arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration.  The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise agreed by the parties. </p>
                <p className="paraColorChange">(e) <i>Time Limits.</i>  If you or FSNET pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim. </p>
                <p className="paraColorChange">(f) <i>Authority of Arbitrator.</i>  If arbitration is initiated, the arbitrator will decide the rights and liabilities, if any, of you and FSNET, and the dispute will not be consolidated with any other matters or joined with any other cases or parties.  The arbitrator shall have the authority to grant motions dispositive of all or part of any claim.  The arbitrator shall have the authority to award monetary damages, and to grant any non-monetary remedy or relief available to an individual under applicable law, the AAA Rules, and the Terms.  The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded.  The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have.  The award of the arbitrator is final and binding upon you and FSNET. </p>
                <p className="paraColorChange">(g) <i>Waiver of Jury Trial.</i>  THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement.  Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in a court and are subject to very limited review by a court.  In the event any litigation should arise between you and FSNET in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND THE BESSEMER VENTURE PARTNERS  WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge. </p>
                <p className="paraColorChange">(h) <i>Waiver of Class or Consolidated Actions.</i>  ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.</p>
                <p className="paraColorChange">(i) <i>Confidentiality.</i>  All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential.  The parties agree to maintain confidentiality unless otherwise required by law.  This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief. </p>
                <p className="paraColorChange">(j) <i>Severability.</i>  If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect. </p>
                <p className="paraColorChange">(k) <i>Right to Waive.</i>  Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted.  Such waiver shall not waive or affect any other portion of this Arbitration Agreement. </p>
                <p className="paraColorChange">(l) <i>Survival of Agreement.</i>  This Arbitration Agreement will survive the termination of your relationship with FSNET.</p>
                <p className="paraColorChange">(m) <i>Small Claims Court.</i>  Notwithstanding the foregoing, either you or FSNET may bring an individual action in small claims court. </p>
                <p className="paraColorChange">(n) <i>Emergency Equitable Relief.</i>  Notwithstanding the foregoing, either party may seek emergency equitable relief before a state or federal court in order to maintain the status quo pending arbitration.  A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement. </p>
                <p className="paraColorChange">(o) <i>Claims Not Subject to Arbitration.</i>  Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark or trade secrets shall not be subject to this Arbitration Agreement. </p>
                <p className="paraColorChange">(p) <i>Courts.</i>  In any circumstances where the foregoing Arbitration Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within San Francisco, California, for such purpose.</p>
                <h4>Miscellaneous</h4>
                <p>These Terms and our relationship with you shall be governed by the laws of the State of New York, without regard to its conflict of law provisions. Our failure to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is found to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in that provision and the other provisions of these Terms remain in full force and effect.  The Terms are the final, complete, and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
                <h4>Questions</h4>
                <p>The mailing address listed above. We will do our best to address your concerns.</p>
                <h5><b>Effective Date</b></h5>
                <p className="paraColorChange">August 1, 2018 </p>
            </div>
        );
    }
}

export default TermsAndConditionsComponent;

